CREATE DATABASE bdEtec
GO
USE bdEtec
CREATE TABLE tb2A(
	rmAluno INT PRIMARY KEY NOT NULL
	,nomeAluno VARCHAR(50) NOT NULL
	,statusAluno VARCHAR(9) NOT NULL
)

CREATE TABLE tb2B(
	rmAluno INT PRIMARY KEY NOT NULL
	,nomeAluno VARCHAR(50) NOT NULL
	,statusAluno VARCHAR(9) NOT NULL
)

CREATE TABLE tbTerceiro(
	rmAluno INT PRIMARY KEY NOT NULL
	,nomeAluno VARCHAR(50) NOT NULL
	,statusAluno VARCHAR(9) NOT NULL
)